export default {
  sliderDisplay: [
    { id: 0, imageLink: require("../assets/images/1.jpg") },
    { id: 1, imageLink: require("../assets/images/2.png") },
    { id: 2, imageLink: require("../assets/images/3.jpg") },
    { id: 3, imageLink: require("../assets/images/4.png") },
    { id: 4, imageLink: require("../assets/images/5.jpg") },
    { id: 5, imageLink: require("../assets/images/6.jpg") },
    { id: 6, imageLink: require("../assets/images/7.jpg") },
  ],
  show: true,
  noShow: false,
  currentHeader: null,
  carsFromAPI: [],
  user: null,
  currentUser: [],
  errorMessage: null,
  productDetailsDisplay: null,
  shoppingCart: null,
  category: null,
};
